[package]
edition = "2021"
name = "p04_concurrency"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7" }
anyhow = "1"
futures = "0.3"
axum = { version = "0.8", features = ["macros"] }
